### ISSUE TITLE
Two Entries in "programs and features"

### ISSUE THREAD

**Issue by jow609** [letsdoautomation/group-policy#2]
Hi together,

First of all many thanks for your video and github entry "Packaging EXE into MSI for Group Policy software deployment using WiX toolset CLI". Everything worked fine for me and I was able to deploy my .msi by GPO. Unfortunately I saw that every installation creates two entries in "Programs and Features". You can also see that behaviour in your Youtube Video:

![2024-08-23_16h18_35](https://github.com/user-attachments/assets/fd760864-648d-4618-9a8e-2a7d9e25f3ad)

Is there any simple solution to fix that issue?

Kind regards

Johannes

**Comment by letsdoautomation** [comment]
thats kinda by design and it needs to exist because that makes troubleshooting easier, but if you really want to remove it then its possible to hide it
https://github.com/letsdoautomation/wix-toolset-4-cli/tree/main/Create%20Notepad%2B%2B%20MSI%20installation%20file

Here you will find sample configuration file that includes configuration for hiding it and it will still exist, but you will not be able to see it in add or remove programs list
